# This file was *autogenerated* from the file /home/lsimons/RubymineProjects/calc/public/sage/exec.sage.
from sage.all_cmdline import *   # import sage library
x = var('x')
y = var('y')
z = var('z')
print "Hello"
print x + y / z
